name: "Verify PR Description"
description: "Ensure the GH PR description is filled out"

inputs:
  PR_ID:
    description: "PR ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup CI
      uses: tahminator/pipeline/actions/setup@ff36293f28519b2b90d7e28918a6885d9baf019e # 1.0.90
      with:
        LINT_CI: true

    - name: Run script
      id: run_script
      shell: bash
      run: bun .github/scripts/pr-description-check --prId=${{ inputs.PR_ID }}
