# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: E2E tests
run-name: Running E2E tests

concurrency:
  group: deploy-staging-pr-${{ inputs.prId }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  schedule:
    - cron: "18 17 * * *" # 12:17 PM ET daily
  workflow_dispatch:

jobs:
  runE2E:
    name: "Run E2E"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup CI
        uses: tahminator/pipeline/actions/setup@a424f92d486342e1255fcdf377a7569eb230aabe # 1.0.97
        with:
          LINT_CI: true
          SECRETS: ${{ toJSON(secrets) }}
          INSTALL_PNPM: "true"
          PNPM_VERSION: "10.24.0"
          PNPM_CACHE: "true"
          PNPM_CACHE_DEPENDENCY_PATH: js/pnpm-lock.yaml
          PNPM_PACKAGE_JSON_FILE: js/package.json
          INSTALL_JAVA: "true"
          JAVA_VERSION: "25"
          JAVA_CACHE_PATH: |
            ~/.m2
            ~/repository
          JAVA_CACHE_KEY: ${{ github.job }}-${{ hashFiles('**/pom.xml') }}

      - name: Run script
        shell: bash
        # set --skip-discord-message=true when you want to test this to avoid spamming the server
        run: bun run .github/scripts/test/run-e2e-tests.ts --skip-discord-message=false --action-url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
