name: PR Help Comment
run-name: PR Help Comment

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  prHelpComment:
    name: PR Help Comment
    runs-on: ubuntu-latest

    steps:
      - name: Help Comment
        uses: actions/checkout@v6

      - name: Setup CI
        uses: tahminator/pipeline/actions/setup@a424f92d486342e1255fcdf377a7569eb230aabe # 1.0.97
        with:
          LINT_CI: true
          SECRETS: ${{ toJSON(secrets) }}

      - name: Run script
        shell: bash
        run: bun run .github/scripts/help-message --pr-id=${{ github.event.pull_request.number }}
